# Generated by Django 6.0 on 2025-12-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='uplaoder',
            new_name='uploader',
        ),
    ]
