# Generated by Django 6.0 on 2026-01-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_uplaoder_photo_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
